VMC: TVirtualMCStack Class Reference
TVirtualMCStack Class Reference abstract
Interface to a user defined particles stack.
#include <TVirtualMCStack.h>
Public Member Functions
TVirtualMCStack ()
Default constructor.
virtual ~TVirtualMCStack ()
Destructor.
virtual void PushTrack (Int_t toBeDone, Int_t parent, Int_t pdg, Double_t px, Double_t py, Double_t pz, Double_t e, Double_t vx, Double_t vy, Double_t vz, Double_t tof, Double_t polx, Double_t poly, Double_t polz, TMCProcess mech, Int_t &ntr, Double_t weight, Int_t is)=0
Create a new particle and push into stack;.
virtual TParticle * PopNextTrack (Int_t &itrack)=0
The stack has to provide two pop mechanisms: The first pop mechanism required.
virtual TParticle * PopPrimaryForTracking (Int_t i)=0
The second pop mechanism required.
virtual void SetCurrentTrack (Int_t trackNumber)=0
Set the current track number.
virtual Int_t GetNtrack () const =0
Total number of tracks.
virtual Int_t GetNprimary () const =0
Total number of primary tracks.
virtual TParticle * GetCurrentTrack () const =0
Current track particle.
virtual Int_t GetCurrentTrackNumber () const =0
Current track number.
virtual Int_t GetCurrentParentTrackNumber () const =0
Number of the parent of the current track.
Detailed Description
Interface to a user defined particles stack.
Definition at line 33 of file TVirtualMCStack.h.
Constructor & Destructor Documentation
TVirtualMCStack()
TVirtualMCStack::TVirtualMCStack ()
Default constructor.
Definition at line 33 of file TVirtualMCStack.cxx.
Referenced by GetCurrentParentTrackNumber(), TMCManagerStack::SetUserStack(), TMCManagerStack::TMCManager, and TMCManagerStack::TMCManagerStack().
~TVirtualMCStack()
TVirtualMCStack::~TVirtualMCStack () virtual
Destructor.
Definition at line 38 of file TVirtualMCStack.cxx.
Member Function Documentation
PushTrack()
virtual void TVirtualMCStack::PushTrack (Int_t toBeDone, Int_t parent, Int_t pdg, Double_t px, Double_t py, Double_t pz, Double_t e, Double_t vx, Double_t vy, Double_t vz, Double_t tof, Double_t polx, Double_t poly, Double_t polz, TMCProcess mech, Int_t & ntr, Double_t weight, Int_t is) pure virtual
Create a new particle and push into stack;.
toBeDone - 1 if particles should go to tracking, 0 otherwise
parent - number of the parent track, -1 if track is primary
pdg - PDG encoding
px, py, pz - particle momentum [GeV/c]
e - total energy [GeV]
vx, vy, vz - position [cm]
tof - time of flight [s]
polx, poly, polz - polarization
mech - creator process VMC code
ntr - track number (is filled by the stack
weight - particle weight
is - generation status code
Implemented in TMCManagerStack.
PopNextTrack()
virtual TParticle * TVirtualMCStack::PopNextTrack (Int_t & itrack) pure virtual
The stack has to provide two pop mechanisms: The first pop mechanism required.
Pop all particles with toBeDone = 1, both primaries and seconadies
Implemented in TMCManagerStack.
PopPrimaryForTracking()
virtual TParticle * TVirtualMCStack::PopPrimaryForTracking (Int_t i) pure virtual
The second pop mechanism required.
Pop only primary particles with toBeDone = 1, stacking of secondaries is done by MC
Implemented in TMCManagerStack.
SetCurrentTrack()
virtual void TVirtualMCStack::SetCurrentTrack (Int_t trackNumber) pure virtual
Set the current track number.
Implemented in TMCManagerStack.
GetNtrack()
virtual Int_t TVirtualMCStack::GetNtrack () const pure virtual
Total number of tracks.
Implemented in TMCManagerStack.
GetNprimary()
virtual Int_t TVirtualMCStack::GetNprimary () const pure virtual
Total number of primary tracks.
Implemented in TMCManagerStack.
GetCurrentTrack()
virtual TParticle * TVirtualMCStack::GetCurrentTrack () const pure virtual
Current track particle.
Implemented in TMCManagerStack.
GetCurrentTrackNumber()
virtual Int_t TVirtualMCStack::GetCurrentTrackNumber () const pure virtual
Current track number.
Implemented in TMCManagerStack.
GetCurrentParentTrackNumber()
virtual Int_t TVirtualMCStack::GetCurrentParentTrackNumber () const pure virtual
Number of the parent of the current track.
Implemented in TMCManagerStack.
The documentation for this class was generated from the following files:
source/include/TVirtualMCStack.h
source/src/TVirtualMCStack.cxx