VMC: TVirtualMCSensitiveDetector Class Reference
TVirtualMCSensitiveDetector Class Reference abstract
Interface to a user defined sensitive detector.
#include <TVirtualMCSensitiveDetector.h>
Public Member Functions
TVirtualMCSensitiveDetector (const char *name, const char *title="")
Standard constructor.
TVirtualMCSensitiveDetector (const TString &name, const TString &title="")
Standard constructor.
virtual ~TVirtualMCSensitiveDetector ()
Destructor.
virtual void Initialize ()=0
Initialize detector.
virtual void ProcessHits ()=0
Process hits.
virtual void EndOfEvent ()=0
End of event.
Protected Member Functions
TVirtualMCSensitiveDetector ()
Default constructor.
TVirtualMCSensitiveDetector (const TVirtualMCSensitiveDetector &rhs)
Copy constructor.
TVirtualMCSensitiveDetector & operator= (const TVirtualMCSensitiveDetector &rhs)
Assignment operator.
Detailed Description
Interface to a user defined sensitive detector.
Definition at line 32 of file TVirtualMCSensitiveDetector.h.
Constructor & Destructor Documentation
TVirtualMCSensitiveDetector() [1/4]
TVirtualMCSensitiveDetector::TVirtualMCSensitiveDetector (const char * name, const char * title = "")
Standard constructor.
Definition at line 33 of file TVirtualMCSensitiveDetector.cxx.
Referenced by EndOfEvent(), operator=(), and TVirtualMCSensitiveDetector().
TVirtualMCSensitiveDetector() [2/4]
TVirtualMCSensitiveDetector::TVirtualMCSensitiveDetector (const TString & name, const TString & title = "")
Standard constructor.
Definition at line 38 of file TVirtualMCSensitiveDetector.cxx.
~TVirtualMCSensitiveDetector()
TVirtualMCSensitiveDetector::~TVirtualMCSensitiveDetector () virtual
Destructor.
Definition at line 61 of file TVirtualMCSensitiveDetector.cxx.
TVirtualMCSensitiveDetector() [3/4]
TVirtualMCSensitiveDetector::TVirtualMCSensitiveDetector () protected
Default constructor.
Definition at line 46 of file TVirtualMCSensitiveDetector.cxx.
TVirtualMCSensitiveDetector() [4/4]
TVirtualMCSensitiveDetector::TVirtualMCSensitiveDetector (const TVirtualMCSensitiveDetector & rhs) protected
Copy constructor.
Copy constructor
Definition at line 51 of file TVirtualMCSensitiveDetector.cxx.
Member Function Documentation
Initialize()
virtual void TVirtualMCSensitiveDetector::Initialize () pure virtual
Initialize detector.
Called at initialization of geometry before MCApplication::InitGeometry().
ProcessHits()
virtual void TVirtualMCSensitiveDetector::ProcessHits () pure virtual
Process hits.
Called at each step when track pass through the associated volume
EndOfEvent()
virtual void TVirtualMCSensitiveDetector::EndOfEvent () pure virtual
End of event.
Called at end of event before MCApplication::FinishEvent().
operator=()
TVirtualMCSensitiveDetector & TVirtualMCSensitiveDetector::operator= (const TVirtualMCSensitiveDetector & rhs) protected
Assignment operator.
Definition at line 66 of file TVirtualMCSensitiveDetector.cxx.
The documentation for this class was generated from the following files:
source/include/TVirtualMCSensitiveDetector.h
source/src/TVirtualMCSensitiveDetector.cxx