VMC: TVirtualMCApplication Class Reference
TVirtualMCApplication Class Reference abstract
Interface to a user Monte Carlo application.
#include <TVirtualMCApplication.h>
Public Member Functions
TVirtualMCApplication (const char *name, const char *title)
Standard constructor.
TVirtualMCApplication ()
Default constructor.
virtual ~TVirtualMCApplication ()
Destructor.
void RequestMCManager ()
Request a TMCManager which is required if multiple engines should be run.
void Register (TVirtualMC *mc)
Register the an engine.
TVirtualMC * GetMC () const
Return the transport engine registered to this application.
virtual void ConstructGeometry ()=0
Construct user geometry.
virtual Bool_t MisalignGeometry ()
Misalign user geometry (optional)
virtual void ConstructOpGeometry ()
Define parameters for optical processes (optional)
virtual void ConstructSensitiveDetectors ()
Define sensitive detectors (optional)
virtual void InitGeometry ()=0
Initialize geometry (Usually used to define sensitive volumes IDs)
virtual void AddParticles ()
Add user defined particles (optional)
virtual void AddIons ()
Add user defined ions (optional)
virtual void GeneratePrimaries ()=0
Generate primary particles.
virtual void BeginEvent ()=0
Define actions at the beginning of the event.
virtual void BeginPrimary ()=0
Define actions at the beginning of the primary track.
virtual void PreTrack ()=0
Define actions at the beginning of each track.
virtual void Stepping ()=0
Define action at each step.
virtual void PostTrack ()=0
Define actions at the end of each track.
virtual void FinishPrimary ()=0
Define actions at the end of the primary track.
virtual void EndOfEvent ()
Define actions at the end of the event before calling SD's end of the event.
virtual void FinishEvent ()=0
Define actions at the end of the event.
virtual Double_t TrackingRmax () const
Define maximum radius for tracking (optional)
virtual Double_t TrackingZmax () const
Define maximum z for tracking (optional)
virtual void Field (const Double_t *x, Double_t *b) const
Calculate user field b at point x.
virtual void GeaneStepping ()
Define action at each step for Geane.
virtual TVirtualMCApplication * CloneForWorker () const
Clone MC application on worker.
virtual void InitForWorker () const
Const Initialize MC application on worker - now deprecated Use new non-const InitOnWorker() instead.
virtual void BeginWorkerRun () const
Const Define actions at the beginning of the worker run if needed - now deprecated Use new non-const BeginRunOnWorker() instead.
virtual void FinishWorkerRun () const
Const Define actions at the end of the worker run if needed - now deprecated Use new non-const FinishRunOnWorker() instead.
virtual void InitOnWorker ()
Initialize MC application on worker.
virtual void BeginRunOnWorker ()
Define actions at the beginning of the worker run if needed.
virtual void FinishRunOnWorker ()
Define actions at the end of the worker run if needed.
virtual void Merge (TVirtualMCApplication *)
Merge the data accumulated on workers to the master if needed.
Static Public Member Functions
static TVirtualMCApplication * Instance ()
Static access method.
Protected Attributes
TVirtualMC * fMC
The current transport engine in use.
TMCManager * fMCManager
Pointer to requested TMCManager which will only be instantiated by a call to RequestMCManager()
Static Private Attributes
static TMCThreadLocal TVirtualMCApplication * fgInstance = nullptr
Singleton instance.
static Bool_t fLockMultiThreading = kFALSE
Forbid multithreading mode if multi run via global static flag.
Detailed Description
Interface to a user Monte Carlo application.
Definition at line 36 of file TVirtualMCApplication.h.
Constructor & Destructor Documentation
TVirtualMCApplication::TVirtualMCApplication (const char * name, const char * title)
Standard constructor.
Definition at line 40 of file TVirtualMCApplication.cxx.
TVirtualMCApplication::TVirtualMCApplication ()
Default constructor.
Definition at line 63 of file TVirtualMCApplication.cxx.
TVirtualMCApplication::~TVirtualMCApplication () virtual
Destructor.
Definition at line 75 of file TVirtualMCApplication.cxx.
Member Function Documentation
TVirtualMCApplication * TVirtualMCApplication::Instance () static
Static access method.
Definition at line 88 of file TVirtualMCApplication.cxx.
Referenced by TVirtualMC::TVirtualMC().
void TVirtualMCApplication::RequestMCManager ()
Request a TMCManager which is required if multiple engines should be run.
For backwards compatibility provide a static GetMC method.
Definition at line 98 of file TVirtualMCApplication.cxx.
void TVirtualMCApplication::Register (TVirtualMC * mc)
Register the an engine.
/// Register the an engine.
Definition at line 111 of file TVirtualMCApplication.cxx.
Referenced by TVirtualMC::TVirtualMC().
TVirtualMC * TVirtualMCApplication::GetMC () const
Return the transport engine registered to this application.
Return the current transport engine in use.
Definition at line 129 of file TVirtualMCApplication.cxx.
virtual void TVirtualMCApplication::ConstructGeometry () pure virtual
Construct user geometry.
Referenced by TMCManager::Register().
virtual Bool_t TVirtualMCApplication::MisalignGeometry () inline virtual
Misalign user geometry (optional)
Definition at line 68 of file TVirtualMCApplication.h.
Referenced by TMCManager::Register().
virtual void TVirtualMCApplication::ConstructOpGeometry () inline virtual
Define parameters for optical processes (optional)
Definition at line 71 of file TVirtualMCApplication.h.
Referenced by TMCManager::Register().
virtual void TVirtualMCApplication::ConstructSensitiveDetectors () inline virtual
Define sensitive detectors (optional)
Definition at line 74 of file TVirtualMCApplication.h.
virtual void TVirtualMCApplication::InitGeometry () pure virtual
Initialize geometry (Usually used to define sensitive volumes IDs)
Referenced by ConstructSensitiveDetectors().
virtual void TVirtualMCApplication::AddParticles () inline virtual
Add user defined particles (optional)
Definition at line 81 of file TVirtualMCApplication.h.
virtual void TVirtualMCApplication::AddIons () inline virtual
Add user defined ions (optional)
Definition at line 84 of file TVirtualMCApplication.h.
virtual void TVirtualMCApplication::GeneratePrimaries () pure virtual
Generate primary particles.
Referenced by AddIons(), and TMCManager::PrepareNewEvent().
virtual void TVirtualMCApplication::BeginEvent () pure virtual
Define actions at the beginning of the event.
Referenced by AddIons(), and TMCManager::Run().
virtual void TVirtualMCApplication::BeginPrimary () pure virtual
Define actions at the beginning of the primary track.
Referenced by AddIons().
virtual void TVirtualMCApplication::PreTrack () pure virtual
Define actions at the beginning of each track.
Referenced by AddIons().
virtual void TVirtualMCApplication::Stepping () pure virtual
Define action at each step.
Referenced by AddIons().
virtual void TVirtualMCApplication::PostTrack () pure virtual
Define actions at the end of each track.
Referenced by AddIons().
virtual void TVirtualMCApplication::FinishPrimary () pure virtual
Define actions at the end of the primary track.
Referenced by AddIons().
virtual void TVirtualMCApplication::EndOfEvent () inline virtual
Define actions at the end of the event before calling SD's end of the event.
Definition at line 108 of file TVirtualMCApplication.h.
virtual void TVirtualMCApplication::FinishEvent () pure virtual
Define actions at the end of the event.
Referenced by EndOfEvent(), and TMCManager::Run().
virtual Double_t TVirtualMCApplication::TrackingRmax () const inline virtual
Define maximum radius for tracking (optional)
Definition at line 114 of file TVirtualMCApplication.h.
virtual Double_t TVirtualMCApplication::TrackingZmax () const inline virtual
Define maximum z for tracking (optional)
Definition at line 117 of file TVirtualMCApplication.h.
void TVirtualMCApplication::Field (const Double_t * x, Double_t * b) const inline virtual
Calculate user field b at point x.
Definition at line 171 of file TVirtualMCApplication.h.
Referenced by TrackingZmax().
virtual void TVirtualMCApplication::GeaneStepping () inline virtual
Define action at each step for Geane.
Definition at line 123 of file TVirtualMCApplication.h.
virtual TVirtualMCApplication* TVirtualMCApplication::CloneForWorker () const inline virtual
Clone MC application on worker.
Definition at line 127 of file TVirtualMCApplication.h.
virtual void TVirtualMCApplication::InitForWorker () const inline virtual
Const Initialize MC application on worker - now deprecated Use new non-const InitOnWorker() instead.
Definition at line 131 of file TVirtualMCApplication.h.
virtual void TVirtualMCApplication::BeginWorkerRun () const inline virtual
Const Define actions at the beginning of the worker run if needed - now deprecated Use new non-const BeginRunOnWorker() instead.
Definition at line 134 of file TVirtualMCApplication.h.
virtual void TVirtualMCApplication::FinishWorkerRun () const inline virtual
Const Define actions at the end of the worker run if needed - now deprecated Use new non-const FinishRunOnWorker() instead.
Definition at line 137 of file TVirtualMCApplication.h.
virtual void TVirtualMCApplication::InitOnWorker () inline virtual
Initialize MC application on worker.
Definition at line 140 of file TVirtualMCApplication.h.
virtual void TVirtualMCApplication::BeginRunOnWorker () inline virtual
Define actions at the beginning of the worker run if needed.
Definition at line 142 of file TVirtualMCApplication.h.
virtual void TVirtualMCApplication::FinishRunOnWorker () inline virtual
Define actions at the end of the worker run if needed.
Definition at line 144 of file TVirtualMCApplication.h.
virtual void TVirtualMCApplication::Merge (TVirtualMCApplication *) inline virtual
Merge the data accumulated on workers to the master if needed.
Definition at line 146 of file TVirtualMCApplication.h.
Member Data Documentation
TVirtualMC* TVirtualMCApplication::fMC protected
The current transport engine in use.
In case of a multi-run the TMCManager will update this whenever the engine changes.
Definition at line 151 of file TVirtualMCApplication.h.
Referenced by GetMC(), Register(), RequestMCManager(), and TVirtualMCApplication().
TMCManager* TVirtualMCApplication::fMCManager protected
Pointer to requested TMCManager which will only be instantiated by a call to RequestMCManager()
Definition at line 155 of file TVirtualMCApplication.h.
Referenced by Register(), RequestMCManager(), TVirtualMCApplication(), and ~TVirtualMCApplication().
TMCThreadLocal TVirtualMCApplication * TVirtualMCApplication::fgInstance = nullptr static private
Singleton instance.
Definition at line 161 of file TVirtualMCApplication.h.
Referenced by Instance(), TVirtualMCApplication(), and ~TVirtualMCApplication().
Bool_t TVirtualMCApplication::fLockMultiThreading = kFALSE static private
Forbid multithreading mode if multi run via global static flag.
Definition at line 166 of file TVirtualMCApplication.h.
Referenced by RequestMCManager(), and TVirtualMCApplication().
The documentation for this class was generated from the following files:
source/include/TVirtualMCApplication.h
source/src/TVirtualMCApplication.cxx